### ISSUE TITLE
Pending fixes on the Contribution Requirements

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/contribution-requirements#24]
We need to delete the dead CREDITS link - I think we should replace with something like: https://opensource.guide/

I think this might work as a code of conduct: https://www.wired.com/story/woman-bringing-civility-to-open-source-projects/

And  this: https://choosealicense.com/

And some template for a CONTRIBUTING file

It may be that the CREDITS file should be AUTHORS - 

Open Source Guides
https://opensource.guide

The Woman Bringing Civility to Open Source Projects
https://www.wired.com

Choose an open source license
https://choosealicense.com
19:55
FIWARE already has a CoC. did you know that?
statement
not question

Jason, 19:57
I did not know. None of the projects has a CoC. We should use it or use a boilerplate CoC from Open source. At least a link would be nice.

19:57

Code of Conduct - FIWARE
https://www.fiware.org
if you want to be a member you need to sign it

**Comment by jason-fox** [comment]
closed by #40
